using System;
using System.Collections.Generic;
using System.CommandLine;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Threading;
using System.Threading.Tasks;
using Vion.Dale.Cli.Output;

namespace Vion.Dale.Cli.Commands
{
    /// <summary>
    ///     The scenario verbs (RFC 0006 R4). Per the CLI's rules they carry no SDK dependency — they operate
    ///     on <c>*.scenario.json</c> files, the wired-host configuration export
    ///     (<c>dale dev --export-config</c>), and the running host's localhost <c>/api</c>. The C#
    ///     <c>ScenarioRunner</c> stays the one authoritative evaluator; <c>validate</c> is a deliberately
    ///     lite, language-neutral mirror of its up-front checks (the same checks a Python runner would
    ///     implement), built for catching renames fast in CI.
    /// </summary>
    public static class ScenarioCommand
    {
        public static Command Create()
        {
            var command = new Command("scenario", "Work with *.scenario.json files (RFC 0006): run, validate, generate the editor schema, scaffold a C# test, open in the Player");
            command.Subcommands.Add(CreateRun());
            command.Subcommands.Add(CreateValidate());
            command.Subcommands.Add(CreateSchema());
            command.Subcommands.Add(CreateScaffold());
            command.Subcommands.Add(CreateOpen());
            return command;
        }

        // Emits a typed C# test from a scenario file — pure file codegen (no SDK dependency: the CLI parses
        // the JSON itself and the generated code references Vion.Dale.DevHost types that live in the
        // consumer's test project, never here). The scenario vocabulary is a strict subset of C#, so the
        // arrange/stimulate half (setup + steps) is total via ScenarioRunner.ApplyAsync; the human judgments
        // become TODO assertions, and the consumer wires the topology-specific host in CreateHostAsync.
        internal static string EmitScaffold(JsonNode scenario, string ns, string scenariosDir)
        {
            var id = scenario["id"]!.GetValue<string>();
            var pascal = ToPascalCase(id);
            var topology = scenario["topology"]?.GetValue<string>() ?? "<topology>";
            var title = scenario["title"]?.GetValue<string>();
            var specs = (scenario["specs"] as JsonArray)?.Select(s => s?.GetValue<string>()).Where(s => s is not null).ToList() ?? new List<string?>();

            var code = new StringBuilder();
            code.AppendLine("// <auto-generated>");
            code.AppendLine($"//   Scaffolded by `dale scenario scaffold {id}` from {scenariosDir}/{id}.scenario.json (RFC 0006 composition rule).");
            code.AppendLine("//   ScenarioRunner.ApplyAsync runs the scenario's setup + ordered steps (acked) against the wired host;");
            code.AppendLine("//   add the assertions the JSON vocabulary can't express below, and implement CreateHostAsync.");
            code.AppendLine("//   Regenerating overwrites this file — move or rename it once you start editing.");
            code.AppendLine("// </auto-generated>");
            code.AppendLine("using System.Threading.Tasks;");
            code.AppendLine("using Vion.Dale.DevHost;");
            code.AppendLine("using Vion.Dale.DevHost.Scenarios;");
            code.AppendLine("using Xunit;");
            code.AppendLine();
            code.AppendLine($"namespace {ns}");
            code.AppendLine("{");
            if (title is not null)
            {
                code.AppendLine($"    // {CommentSafe(title)}");
            }

            code.AppendLine($"    public class {pascal}Scenario");
            code.AppendLine("    {");
            code.AppendLine($"        private const string ScenarioId = {CSharpString(id)};");
            code.AppendLine($"        private const string ScenariosDirectory = {CSharpString(scenariosDir)};");
            code.AppendLine();
            code.AppendLine($"        // Topology: {topology}");
            if (specs.Count > 0)
            {
                code.AppendLine($"        // Specs: {string.Join(", ", specs)}");
            }

            code.AppendLine("        [Fact]");
            code.AppendLine($"        public async Task {pascal}()");
            code.AppendLine("        {");
            code.AppendLine("            await using var host = await CreateHostAsync();");
            code.AppendLine("            await host.StartAsync();");
            code.AppendLine();
            code.AppendLine("            // Applies the scenario's setup + ordered steps (acked):");
            foreach (var line in DescribeSection(scenario["setup"]).Concat(DescribeSection(scenario["steps"])))
            {
                code.AppendLine($"            //   {line}");
            }

            code.AppendLine("            await ScenarioRunner.ApplyAsync(ScenarioId, host.Control, ScenariosDirectory);");

            var watch = (scenario["watch"] as JsonArray)?.Select(w => w?.GetValue<string>()).Where(w => w is not null).ToList() ?? new List<string?>();
            if (watch.Count > 0)
            {
                code.AppendLine();
                code.AppendLine("            // Watch — the signals this scenario cares about (read them with host.Control.GetProperty):");
                foreach (var path in watch)
                {
                    code.AppendLine($"            //   {path}");
                }
            }

            code.AppendLine();
            code.AppendLine("            // Hand-written assertions — the judgments the scenario leaves to a human reviewer:");
            var judgments = scenario["judge"] as JsonArray ?? new JsonArray();
            if (judgments.Count == 0)
            {
                code.AppendLine("            // (none authored — add your own)");
            }

            foreach (var judgment in judgments)
            {
                var text = judgment?["text"]?.GetValue<string>() ?? "";
                var spec = judgment?["spec"]?.GetValue<string>();
                code.AppendLine($"            // TODO{(spec is null ? "" : $" [{spec}]")}: {CommentSafe(text)}");
            }

            code.AppendLine("        }");
            code.AppendLine();
            code.AppendLine($"        // TODO: build the wired host this scenario's topology (\"{topology}\") expects, e.g.:");
            code.AppendLine($"        //   var config = DevConfigurationBuilder.Create().WithTopologyName({CSharpString(topology)})./* ...presets... */.Build();");
            code.AppendLine("        //   return DevHostBuilder.Create().WithDi<DependencyInjection>().WithConfiguration(config).Build();");
            code.AppendLine("        private static Task<IDevHost> CreateHostAsync() =>");
            code.AppendLine($"            throw new System.NotImplementedException(\"Build the '{topology}' DevHost this scenario runs against.\");");
            code.AppendLine("    }");
            code.AppendLine("}");
            return code.ToString();
        }

        private static Option<int> PortOption()
        {
            return new Option<int>("--port") { Description = "Port of the running DevHost (default 5000).", DefaultValueFactory = _ => 5000 };
        }

        private static Command CreateRun()
        {
            var run = new Command("run", "Execute a scenario against the running DevHost and report the result — the same report the Player's copy button produces");
            var idArgument = new Argument<string>("id") { Description = "Scenario id (the file name without .scenario.json)." };
            var portOption = PortOption();
            var restartOption = new Option<bool>("--restart") { Description = "Cancel an active run and take over (the API's ?restart=true)." };
            var forceOption = new Option<bool>("--force") { Description = "Proceed despite a topology mismatch (the Player's run-anyway)." };
            var timeoutOption = new Option<int>("--timeout") { Description = "Seconds to wait for the run to finish (default 600).", DefaultValueFactory = _ => 600 };
            run.Arguments.Add(idArgument);
            run.Options.Add(portOption);
            run.Options.Add(restartOption);
            run.Options.Add(forceOption);
            run.Options.Add(timeoutOption);

            run.SetAction(async (parseResult, cancellationToken) =>
                          {
                              var id = parseResult.GetValue(idArgument)!;
                              var port = parseResult.GetValue(portOption);
                              using var http = NewClient(port);

                              var query = new List<string>();
                              if (parseResult.GetValue(restartOption))
                              {
                                  query.Add("restart=true");
                              }

                              if (parseResult.GetValue(forceOption))
                              {
                                  query.Add("force=true");
                              }

                              HttpResponseMessage apply;
                              try
                              {
                                  apply = await http.PostAsync($"/api/scenarios/{Uri.EscapeDataString(id)}/apply{(query.Count > 0 ? "?" + string.Join("&", query) : "")}",
                                                               null,
                                                               cancellationToken);
                              }
                              catch (HttpRequestException e)
                              {
                                  DaleConsole.Error($"No DevHost reachable on port {port} ({e.Message}). Start one with `dale dev --headless`.");
                                  return 1;
                              }

                              var applyBody = await apply.Content.ReadAsStringAsync(cancellationToken);
                              if (!apply.IsSuccessStatusCode)
                              {
                                  DaleConsole.Error($"apply returned {(int)apply.StatusCode}: {applyBody}");
                                  return 1;
                              }

                              var runId = JsonNode.Parse(applyBody)?["runId"]?.GetValue<string>();
                              var deadline = DateTimeOffset.UtcNow + TimeSpan.FromSeconds(parseResult.GetValue(timeoutOption));
                              JsonNode? report = null;
                              while (DateTimeOffset.UtcNow < deadline)
                              {
                                  var response = await http.GetAsync($"/api/scenarios/{Uri.EscapeDataString(id)}/run", cancellationToken);
                                  if (response.IsSuccessStatusCode)
                                  {
                                      report = JsonNode.Parse(await response.Content.ReadAsStringAsync(cancellationToken));
                                      var current = report?["runId"]?.GetValue<string>();
                                      var status = report?["status"]?.GetValue<string>();
                                      if (current == runId && status != "running")
                                      {
                                          break;
                                      }
                                  }

                                  await Task.Delay(500, cancellationToken);
                              }

                              if (report is null || report["status"]?.GetValue<string>() == "running")
                              {
                                  DaleConsole.Error($"run '{runId}' did not finish within the timeout — it may still be executing.");
                                  return 1;
                              }

                              if (DaleConsole.JsonMode)
                              {
                                  Console.WriteLine(report.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));
                              }
                              else
                              {
                                  RenderReport(report);
                              }

                              return report["status"]?.GetValue<string>() == "succeeded" ? 0 : 1;
                          });

            return run;
        }

        private static Command CreateValidate()
        {
            var validate = new Command("validate",
                                       "Validate every scenario file: structure, name paths, and topology against the wired-host configuration — catches renames fast in CI");
            var dirOption = new Option<string>("--dir") { Description = "Scenarios directory (default ./scenarios).", DefaultValueFactory = _ => "scenarios" };
            var configOption = new Option<string?>("--config")
                               {
                                   Description =
                                       "Configuration export from `dale dev --export-config <file>`. When omitted, the running DevHost's /api/configuration is used.",
                               };
            var portOption = PortOption();
            validate.Options.Add(dirOption);
            validate.Options.Add(configOption);
            validate.Options.Add(portOption);

            validate.SetAction(async (parseResult, cancellationToken) =>
                               {
                                   var dir = parseResult.GetValue(dirOption)!;
                                   if (!Directory.Exists(dir))
                                   {
                                       DaleConsole.Error($"No scenarios directory at '{Path.GetFullPath(dir)}'.");
                                       return 1;
                                   }

                                   var config = await LoadConfigAsync(parseResult.GetValue(configOption), parseResult.GetValue(portOption), cancellationToken);
                                   if (config is null)
                                   {
                                       return 1;
                                   }

                                   var results = new List<object>();
                                   var failed = false;
                                   foreach (var path in Directory.EnumerateFiles(dir, "*.scenario.json").OrderBy(p => p, StringComparer.OrdinalIgnoreCase))
                                   {
                                       var fileName = Path.GetFileName(path);
                                       var outcome = ScenarioFileChecks.Validate(fileName, File.ReadAllText(path), config);
                                       failed |= outcome.Errors.Count > 0;
                                       results.Add(new { file = fileName, skipped = outcome.SkippedForTopology, errors = outcome.Errors });

                                       if (!DaleConsole.JsonMode)
                                       {
                                           if (outcome.Errors.Count > 0)
                                           {
                                               DaleConsole.Error($"{fileName}:");
                                               foreach (var error in outcome.Errors)
                                               {
                                                   DaleConsole.Info($"    ✗ {error}");
                                               }
                                           }
                                           else
                                           {
                                               DaleConsole.Info(outcome.SkippedForTopology is null ? $"  ✓ {fileName}" :
                                                                    $"  - {fileName} (topology '{outcome.SkippedForTopology}' is not the exported one — paths not checked)");
                                           }
                                       }
                                   }

                                   if (DaleConsole.JsonMode)
                                   {
                                       DaleConsole.WriteJsonResult(new { valid = !failed, files = results });
                                   }
                                   else if (!failed)
                                   {
                                       DaleConsole.Success("Validated", $"{results.Count} scenario file(s)");
                                   }

                                   return failed ? 1 : 0;
                               });

            return validate;
        }

        private static Command CreateSchema()
        {
            var schema = new Command("schema",
                                     "Print the scenario JSON Schema, enriched with this topology's actual name paths when a configuration is available — " +
                                     "commit it as scenarios/.dale/scenario.schema.json and reference it from scenario files via \"$schema\" for editor completion");
            var outputOption = new Option<string?>("--output", "-o")
                               {
                                   Description =
                                       "Write to this file instead of printing (conventionally scenarios/.dale/scenario.schema.json, what the files' \"$schema\" points at).",
                               };
            var configOption = new Option<string?>("--config") { Description = "Configuration export to enrich from (default: the running DevHost)." };
            var portOption = PortOption();
            schema.Options.Add(outputOption);
            schema.Options.Add(configOption);
            schema.Options.Add(portOption);

            schema.SetAction(async (parseResult, cancellationToken) =>
                             {
                                 var port = parseResult.GetValue(portOption);

                                 // The generic structural schema ships embedded in the CLI, so `dale scenario
                                 // schema` runs fully offline — the same offline story as `dale scenario
                                 // validate` (DF-10). Enrichment with the actual block/property name paths is
                                 // best-effort: an explicit --config export or a running host supplies them;
                                 // with neither we emit the un-enriched generic schema (a clear, still-useful
                                 // result, not an error).
                                 var document = JsonNode.Parse(LoadEmbeddedGenericSchema())!;

                                 var configPath = parseResult.GetValue(configOption);
                                 JsonNode? config;
                                 if (configPath is not null)
                                 {
                                     config = await LoadConfigAsync(configPath, port, cancellationToken);
                                     if (config is null)
                                     {
                                         // An explicitly requested --config that doesn't load is an error.
                                         return 1;
                                     }
                                 }
                                 else
                                 {
                                     config = await LoadConfigAsync(null, port, cancellationToken, false);
                                     if (config is null && !DaleConsole.JsonMode)
                                     {
                                         DaleConsole.Info("    Note: emitting the generic schema — pass --config <export> or run `dale dev` for name-path completion.");
                                     }
                                 }

                                 if (config is not null)
                                 {
                                     ScenarioFileChecks.EnrichSchemaWithNamePaths(document, config);
                                 }

                                 var json = document.ToJsonString(new JsonSerializerOptions { WriteIndented = true });

                                 // No -o: the schema IS the output (pipe or inspect it) — a schema command
                                 // should show a schema, not write to a magic location.
                                 var output = parseResult.GetValue(outputOption);
                                 if (output is null)
                                 {
                                     Console.WriteLine(json);
                                     return 0;
                                 }

                                 Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);
                                 File.WriteAllText(output, json);

                                 if (DaleConsole.JsonMode)
                                 {
                                     DaleConsole.WriteJsonResult(new { written = Path.GetFullPath(output), enriched = config is not null });
                                 }
                                 else
                                 {
                                     DaleConsole.Success("Wrote", output);
                                     DaleConsole.Info("    Reference it from scenario files for editor completion: \"$schema\": \"./.dale/scenario.schema.json\"");
                                 }

                                 return 0;
                             });

            return schema;
        }

        private static Command CreateScaffold()
        {
            var scaffold = new Command("scaffold",
                                       "Generate a typed C# test from a scenario file — runs the scenario's setup + steps via ScenarioRunner.ApplyAsync, with TODO assertions for its human judgments (RFC 0006 composition rule: the graduation path when a scenario outgrows the format)");
            var idArgument = new Argument<string>("id") { Description = "Scenario id (the file name without .scenario.json)." };
            var dirOption = new Option<string>("--dir") { Description = "Scenarios directory (default ./scenarios).", DefaultValueFactory = _ => "scenarios" };
            var namespaceOption = new Option<string>("--namespace")
                                  { Description = "Namespace for the generated test class (default ScenarioTests).", DefaultValueFactory = _ => "ScenarioTests" };
            var outputOption = new Option<string?>("--output", "-o")
                               {
                                   Description =
                                       "Write to this file (default <Id>ScenarioTest.cs in the current directory); pass '-' to print to stdout.",
                               };
            scaffold.Arguments.Add(idArgument);
            scaffold.Options.Add(dirOption);
            scaffold.Options.Add(namespaceOption);
            scaffold.Options.Add(outputOption);

            scaffold.SetAction((parseResult, cancellationToken) =>
                               {
                                   var id = parseResult.GetValue(idArgument)!;
                                   var dir = parseResult.GetValue(dirOption)!;
                                   var path = Path.Combine(dir, $"{id}.scenario.json");
                                   if (!File.Exists(path))
                                   {
                                       DaleConsole.Error($"No scenario file at '{Path.GetFullPath(path)}' (expected <dir>/{id}.scenario.json).");
                                       return Task.FromResult(1);
                                   }

                                   JsonNode? scenario;
                                   try
                                   {
                                       scenario = JsonNode.Parse(File.ReadAllText(path));
                                   }
                                   catch (JsonException e)
                                   {
                                       DaleConsole.Error($"{id}.scenario.json is not valid JSON: {e.Message}");
                                       return Task.FromResult(1);
                                   }

                                   if (scenario?["id"]?.GetValue<string>() is not { } fileId)
                                   {
                                       DaleConsole.Error($"{id}.scenario.json has no 'id'.");
                                       return Task.FromResult(1);
                                   }

                                   if (!string.Equals(fileId, id, StringComparison.Ordinal))
                                   {
                                       DaleConsole.Error($"the id '{fileId}' inside the file does not match the file name '{id}' — rename one to match.");
                                       return Task.FromResult(1);
                                   }

                                   var code = EmitScaffold(scenario, parseResult.GetValue(namespaceOption)!, dir);

                                   var output = parseResult.GetValue(outputOption);
                                   if (output == "-")
                                   {
                                       Console.WriteLine(code);
                                       return Task.FromResult(0);
                                   }

                                   var outputPath = output ?? $"{ToPascalCase(id)}ScenarioTest.cs";
                                   var outputDir = Path.GetDirectoryName(Path.GetFullPath(outputPath));
                                   if (!string.IsNullOrEmpty(outputDir))
                                   {
                                       Directory.CreateDirectory(outputDir);
                                   }

                                   File.WriteAllText(outputPath, code);

                                   if (DaleConsole.JsonMode)
                                   {
                                       DaleConsole.WriteJsonResult(new { written = Path.GetFullPath(outputPath) });
                                   }
                                   else
                                   {
                                       DaleConsole.Success("Wrote", outputPath);
                                       DaleConsole
                                           .Info("    Implement CreateHostAsync and fill in the TODO assertions, then move the file so a re-scaffold doesn't overwrite your edits.");
                                   }

                                   return Task.FromResult(0);
                               });

            return scaffold;
        }

        // One human-readable comment line per setup/step entry (best-effort; comments only).
        private static IEnumerable<string> DescribeSection(JsonNode? section)
        {
            foreach (var entry in section as JsonArray ?? new JsonArray())
            {
                if (entry is not JsonObject step)
                {
                    continue;
                }

                var label = step["label"]?.GetValue<string>();
                string body;
                if (step["set"] is { } set)
                {
                    body = $"set {set.GetValue<string>()} = {CompactValue(step["value"])}";
                }
                else if (step["digitalInput"] is { } digital)
                {
                    body = $"digitalInput {digital["block"]?.GetValue<string>()}.{digital["contract"]?.GetValue<string>()} = {CompactValue(step["value"])}";
                }
                else if (step["analogInput"] is { } analog)
                {
                    body = $"analogInput {analog["block"]?.GetValue<string>()}.{analog["contract"]?.GetValue<string>()} = {CompactValue(step["value"])}";
                }
                else if (step["waitUntil"] is JsonObject waitUntil)
                {
                    body = $"waitUntil {waitUntil["property"]?.GetValue<string>()} {DescribeComparator(waitUntil)}";
                }
                else if (step["wait"] is JsonObject wait)
                {
                    body = $"wait {wait["seconds"]}s";
                }
                else
                {
                    body = "(step)";
                }

                yield return label is null ? CommentSafe(body) : $"{CommentSafe(body)}   ({CommentSafe(label)})";
            }
        }

        private static string DescribeComparator(JsonObject waitUntil)
        {
            foreach (var op in new[] { "above", "below", "equals", "notEquals" })
            {
                if (waitUntil[op] is { } value)
                {
                    return $"{op} {CompactValue(value)}";
                }
            }

            return "";
        }

        private static string CompactValue(JsonNode? value)
        {
            if (value is null)
            {
                return "(absent)";
            }

            var json = value.ToJsonString();
            return json.Length > 60 ? json.Substring(0, 57) + "…" : json;
        }

        // Slug -> PascalCase identifier (peak-shaving -> PeakShaving); leading digit gets an underscore.
        private static string ToPascalCase(string slug)
        {
            var builder = new StringBuilder();
            var capitalizeNext = true;
            foreach (var c in slug)
            {
                if (!char.IsLetterOrDigit(c))
                {
                    capitalizeNext = true;
                    continue;
                }

                builder.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }

            if (builder.Length == 0)
            {
                return "Scenario";
            }

            return char.IsDigit(builder[0]) ? "_" + builder : builder.ToString();
        }

        private static string CSharpString(string value)
        {
            return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        }

        // Collapse to a single safe `//` comment line.
        private static string CommentSafe(string text)
        {
            return text.Replace("\r", " ").Replace("\n", " ").Trim();
        }

        private static Command CreateOpen()
        {
            var open = new Command("open", "Open a scenario in the running DevHost's Player (the #/scenario/{id} deep link)");
            var idArgument = new Argument<string>("id") { Description = "Scenario id." };
            var portOption = PortOption();
            open.Arguments.Add(idArgument);
            open.Options.Add(portOption);

            open.SetAction((parseResult, cancellationToken) =>
                           {
                               var url = $"http://localhost:{parseResult.GetValue(portOption)}/#/scenario/{Uri.EscapeDataString(parseResult.GetValue(idArgument)!)}";
                               try
                               {
                                   Process.Start(new ProcessStartInfo { FileName = url, UseShellExecute = true });
                               }
                               catch (Exception e)
                               {
                                   DaleConsole.Error($"Could not open the browser: {e.Message}. Navigate to {url} manually.");
                                   return Task.FromResult(1);
                               }

                               DaleConsole.Info($"Opened {url}");
                               return Task.FromResult(0);
                           });

            return open;
        }

        private static HttpClient NewClient(int port)
        {
            return new HttpClient { BaseAddress = new Uri($"http://localhost:{port}"), Timeout = TimeSpan.FromSeconds(30) };
        }

        // Loads the wired-host configuration to resolve name paths against: from a --config export file, or
        // from a running DevHost's /api/configuration. When requireSource is false, an unreachable host is
        // not an error (the caller can proceed without enrichment — see `dale scenario schema`).
        private static async Task<JsonNode?> LoadConfigAsync(string? configPath, int port, CancellationToken cancellationToken, bool requireSource = true)
        {
            if (configPath is not null)
            {
                if (!File.Exists(configPath))
                {
                    DaleConsole.Error($"No configuration export at '{configPath}'. Produce one with `dale dev --export-config {configPath}`.");
                    return null;
                }

                return JsonNode.Parse(File.ReadAllText(configPath));
            }

            using var http = NewClient(port);
            try
            {
                return JsonNode.Parse(await http.GetStringAsync("/api/configuration", cancellationToken));
            }
            catch (HttpRequestException e)
            {
                if (requireSource)
                {
                    DaleConsole.Error($"No configuration source: no --config file given and no DevHost reachable on port {port} ({e.Message}). " +
                                      "Run `dale dev --headless` or export one with `dale dev --export-config <file>`.");
                }

                return null;
            }
        }

        // The generic scenario-file schema, embedded in the CLI assembly (linked from the single source file
        // in Vion.Dale.DevHost — see the .csproj). Reading it here is what lets `dale scenario schema` run
        // without a DevHost (DF-10).
        private static string LoadEmbeddedGenericSchema()
        {
            const string resourceName = "Vion.Dale.Cli.scenario.schema.json";
            var assembly = typeof(ScenarioCommand).Assembly;
            using var stream = assembly.GetManifestResourceStream(resourceName) ??
                               throw new InvalidOperationException($"Embedded resource '{resourceName}' is missing from the CLI assembly.");
            using var reader = new StreamReader(stream);
            return reader.ReadToEnd();
        }

        private static void RenderReport(JsonNode report)
        {
            var status = report["status"]?.GetValue<string>();
            DaleConsole.Info($"scenario {report["scenarioId"]} — {status} (run {report["runId"]})");
            foreach (var error in report["validationErrors"] as JsonArray ?? new JsonArray())
            {
                DaleConsole.Info($"  ✗ {error}");
            }

            void Section(string name)
            {
                var steps = report[name] as JsonArray;
                if (steps is null || steps.Count == 0)
                {
                    return;
                }

                foreach (var step in steps)
                {
                    var glyph = step!["status"]?.GetValue<string>() switch
                    {
                        "ok" => "✓",
                        "failed" => "✗",
                        "skipped" => "⊘",
                        _ => "◌",
                    };
                    var argument = step["argument"]?.GetValue<string>() is { } a ? $" {a}" : "";
                    var elapsed = step["elapsedMs"]?.GetValue<double>() is { } ms ? $" ({Math.Round(ms)} ms)" : "";
                    var detail = step["detail"]?.GetValue<string>() is { } d ? $" — {d}" : "";
                    DaleConsole.Info($"  {glyph} {step["kind"]} {step["target"]}{argument}{elapsed}{detail}");
                }
            }

            Section("setup");
            Section("steps");
            foreach (var judgment in report["judge"] as JsonArray ?? new JsonArray())
            {
                DaleConsole.Info($"  ☐ {judgment!["text"]} (requires human{(judgment["spec"] is { } s ? $" — {s}" : "")})");
            }
        }
    }
}